# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 290c906618d299a6ea9a9660dc531fe0343dadca6792e603df7e58bfa5921a66c1a6407bee272ada0f16e62f34993849761ea2f62651f518b954d9c6e107bd2e

test:
  secret_key_base: dc2d800490829a173d3d7f2b9bea3f9702edfd6cc29636aa758ba96057f16c0f6dc82168e4c8d3b99837ba07a64aaa25ed35e843082c43216f9bdf8832810c7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
